#!/bin/sh

cat << EOS
[options] \\
  --master-charset UTF-8 \\
  --localized-charset UTF-8 \\
  --addendum-charset UTF-8 \\
  --master-language en
[po4a_langs] ja
[po4a_paths] pot/\$master.pot \$lang:po/\$lang/\$master.po
EOS

for markdown in ../src/**/*.md ../README.md; do
  cat << EOS
[type:text] \\
  $markdown \\
  \$lang:\$lang/${markdown#../} \\
  opt:"--option markdown --keep 0"
EOS
done
